# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

#source 'https://github.com/私有仓库地址.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'DeepSleep2' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'SwifterSwift'
  pod 'ZKProgressHUD'
  pod 'Alertift'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'Moya'
  pod 'MoyaSugar'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'DeviceKit'
  pod 'Defaults'
  pod 'NoticeObserveKit'
  pod 'SnapKit'
  pod 'JXPagingView/Paging'
  pod 'JXSegmentedView'
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'JXPopupView'
  pod 'Jelly'
  pod "PickerView"
  pod 'Shimmer'
  
#  pod 'StreamingKit'
#  pod 'SwiftAudioPlayer'

  pod 'FBSDKLoginKit'
  
  pod 'ThinkingSDK'
  # Adjust
  pod 'Adjust'
  # Firebase - 核心类库
  pod 'Firebase/Core'
  # Firebase - 消息推送
  pod 'Firebase/Messaging'
  # Firebase - remote
  pod 'Firebase/RemoteConfig'
  # Firebase - Crash
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'SVGKit', :git => "https://github.com/jojojoe/SVGKit.git", :branch => "3.x"
  
  pod 'HDSwiftCommonTools'
  pod 'lottie-ios'
  
  #  pod 'mopub-ios-sdk'
  pod 'mopub-ios-sdk/Core' #,'~> 5.11.0'
  pod 'mopub-ios-sdk/NativeAds' #,'~> 5.11.0'

  # AppLovin
  pod 'MoPub-Applovin-Adapters'

  # Google (AdMob) #
  pod 'MoPub-AdMob-Adapters'
  
 
  #  Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya/RxSwift'
 
  
  # StoreKit
  pod 'SwiftyStoreKit'
  pod 'TPInAppReceipt'
  
  # SQLite
  pod 'SQLite.swift'
  
  # Download
  pod 'Tiercel'
  
  # 公共
  pod 'SEExtensions'
  #, :path=> '/Users/jojo/Documents/WorkSpace/图像线/GitLib/SEExtension/'
  pod 'LookinServer', :configurations => ['Debug']

  pod 'SwiftAudioPlayer', :path => '../'

end
